# Source

[Wine quality prediction using PyTorch](https://medium.com/analytics-vidhya/wine-quality-prediction-using-pytorch-2a291670dd66#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjBlNzJkYTFkZjUwMWNhNmY3NTZiZjEwM2ZkN2M3MjAyOTQ3NzI1MDYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIyMTYyOTYwMzU4MzQtazFrNnFlMDYwczJ0cDJhMmphbTRsamRjbXMwMHN0dGcuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiIyMTYyOTYwMzU4MzQtazFrNnFlMDYwczJ0cDJhMmphbTRsamRjbXMwMHN0dGcuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDkxMTc0MTkxNzMyOTg0OTU4MzciLCJoZCI6InByZWRkYXRhLmNvbSIsImVtYWlsIjoidmljdG9yLnBlY2luZUBwcmVkZGF0YS5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmJmIjoxNzAxMTY4MDYyLCJuYW1lIjoiVmljdG9yIFBlY2luZSB8IFByZWRkYXRhIFNvbHV0aW9ucyIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NMRzh2Zk5ZeWlmUVVZakNxMHBBdElsVWNDNi0zejAzYm5lRTg5clNqalY9czk2LWMiLCJnaXZlbl9uYW1lIjoiVmljdG9yIFBlY2luZSIsImZhbWlseV9uYW1lIjoifCBQcmVkZGF0YSBTb2x1dGlvbnMiLCJsb2NhbGUiOiJwdC1CUiIsImlhdCI6MTcwMTE2ODM2MiwiZXhwIjoxNzAxMTcxOTYyLCJqdGkiOiI2Mjk4NDM1MjYyNzY0ZTQxYWRjNjNkZGI4ZTIzMjg4ZDhjODU0NjQxIn0.X9PkBXf0xEbQGAlsMyiOeT5jQ2q7M-Q7QA8XAcC2y0oK6L1c_MYoKas62UQ6mhqab6ZGs8tUFDoFGV6oLrV8IEz9Nzx1-CEbezYfVjtK_delT3WpD33mtctmIyfsJi3wweldaTVtRh8_24YZSuYfiXUjPCJ9O3up4V4i1quFNg7SppfHnFXzA28VIIUVqkumFb0Leb8mk-fPdmBUQSNMZSe-2PzfYDw3RtcKuR32l_7VGhNsuqOh2TUhROfZ0w5cajcGOuM0iR-nZcQxfOpzxeeGpDnnH0rMgY1cZov5UWDHjPieC6JcL1AsX2PoG6ka-lqPuzwepgxURfMC3kjBMA)

# Steps

✔️ Data wrangling

✔️ Data visualization

✔️ Scaling data

✔️ Resampling data

➖ RNN

➖ Loss function

# Libraires

In [235]:
# !pip install plotly -U --quiet

In [212]:
import  torch
import  matplotlib.pyplot as plt
import  numpy as np
import  pandas as pd
import  plotly.express as px

from    google.colab import drive
from    sklearn.model_selection import train_test_split
from    sklearn.preprocessing import StandardScaler
from    imblearn.over_sampling import SMOTE
from    imblearn.combine import SMOTEENN

In [213]:
np.random.seed(31)

In [214]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Dataset

In [215]:
df_wine = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/winequality-red.csv',
                      sep=',',
                      encoding='utf-8')

df_wine

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [216]:
df_wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [217]:
df_wine['quality'].unique()

array([5, 6, 7, 4, 8, 3])

In [218]:
df_wine.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

# Data visualization

In [219]:
fig = px.histogram(df_wine, x='quality')
fig.show()

It's a good practice over-sampling the data to have a equal balance

In [220]:
df_wine['quality'].value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [221]:
maior_quantidade_qualidade = df_wine['quality'].value_counts().max()

maior_quantidade_qualidade

681

# Scalinga and resampling data

In [222]:
X = df_wine.drop(columns='quality')

y = df_wine['quality']

In [223]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

In [224]:
print('Shape of X_scaled: ', X_scaled.shape)
print('Shape of y: ', y.shape)

Shape of X_scaled:  (1599, 11)
Shape of y:  (1599,)


In [225]:
smoteenn = SMOTEENN()

X_smoteenn, y_smoteenn = smoteenn.fit_resample(X_scaled, y)

In [226]:
smote = SMOTE()

X_smote, y_smote = smote.fit_resample(X_scaled, y)

In [227]:
print('Shape of X_smoteenn: ', X_smoteenn.shape)
print('Shape of y_smoteenn: ', y_smoteenn.shape)

print('Shape of X_smote: ', X_smote.shape)
print('Shape of y_smote: ', y_smote.shape)

Shape of X_smoteenn:  (2982, 11)
Shape of y_smoteenn:  (2982,)
Shape of X_smote:  (4086, 11)
Shape of y_smote:  (4086,)


In [228]:
df_wine_smoteenn = pd.DataFrame(np.column_stack((X_smoteenn, y_smoteenn)))

df_wine_smoteenn.rename(columns={0: df_wine.columns[0],
                                   1: df_wine.columns[1],
                                   2: df_wine.columns[2],
                                   3: df_wine.columns[3],
                                   4: df_wine.columns[4],
                                   5: df_wine.columns[5],
                                   6: df_wine.columns[6],
                                   7: df_wine.columns[7],
                                   8: df_wine.columns[8],
                                   9: df_wine.columns[9],
                                   10: df_wine.columns[10],
                                   11: df_wine.columns[11]},
                          inplace=True)

df_wine_smoteenn.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0       1.884668          0.291499     1.997658       -0.240375  -0.286214   
1       1.195232          0.459094     1.124700       -0.311323   2.391755   
2      -0.528360          3.671318    -1.391472        1.214055   0.202621   
3       1.195232         -0.490607     0.765247       -0.737010   1.222800   
4      -0.011282          2.749549    -1.288771        0.610998  -0.073677   

   free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  \
0            -0.561823              0.016184  2.148316 -0.395969  -0.520193   
1            -1.039977             -0.926494  1.406296 -0.979104  -0.166115   
2            -1.039977             -0.987312 -0.077742  2.066156  -0.697233   
3             1.733315              0.046593  0.833882  0.446337   1.191186   
4            -0.944346             -1.078539  1.151890  1.094265  -0.992298   

    alcohol  quality  
0 -1.335715      3.0  
1 -1.898919      3.0  
2  0.260028      3.0  
3 -0.490910      3.0  
4  0.541630      3.0

In [229]:
fig = px.histogram(df_wine_smoteenn, x='quality')

fig.show()

In [230]:
df_wine_smote = pd.DataFrame(np.column_stack((X_smote, y_smote)))

df_wine_smote.rename(columns={0: df_wine.columns[0],
                                   1: df_wine.columns[1],
                                   2: df_wine.columns[2],
                                   3: df_wine.columns[3],
                                   4: df_wine.columns[4],
                                   5: df_wine.columns[5],
                                   6: df_wine.columns[6],
                                   7: df_wine.columns[7],
                                   8: df_wine.columns[8],
                                   9: df_wine.columns[9],
                                   10: df_wine.columns[10],
                                   11: df_wine.columns[11]},
                          inplace=True)

df_wine_smote.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0      -0.528360          0.961877    -1.391472       -0.453218  -0.243707   
1      -0.298547          1.967442    -1.391472        0.043416   0.223875   
2      -0.298547          1.297065    -1.186070       -0.169427   0.096353   
3       1.654856         -1.384443     1.484154       -0.453218  -0.264960   
4      -0.528360          0.961877    -1.391472       -0.453218  -0.243707   

   free sulfur dioxide  total sulfur dioxide   density        pH  sulphates  \
0            -0.466193             -0.379133  0.558274  1.288643  -0.579207   
1             0.872638              0.624363  0.028261 -0.719933   0.128950   
2            -0.083669              0.229047  0.134264 -0.331177  -0.048089   
3             0.107592              0.411500  0.664277 -0.979104  -0.461180   
4            -0.466193             -0.379133  0.558274  1.288643  -0.579207   

    alcohol  quality  
0 -0.960246      5.0  
1 -0.584777      5.0  
2 -0.584777      5.0  
3 -0.584777      6.0  
4 -0.960246      5.0

In [231]:
fig = px.histogram(df_wine_smote, x='quality')

fig.show()

# Train test split

In [232]:
X_train, X_test, y_train, y_test = train_test_split(X_smote, y_smote, test_size=0.3)

print('Shape of X_train: ', X_train.shape)
print('Shape of X_test: ', X_test.shape)
print('Shape of y_train: ', y_train.shape)
print('Shape of y_test: ', y_test.shape)

Shape of X_train:  (2860, 11)
Shape of X_test:  (1226, 11)
Shape of y_train:  (2860,)
Shape of y_test:  (1226,)


# Tensors

In [233]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float)

X_test_tensor = torch.tensor(X_test, dtype=torch.float)

y_train_tensor = torch.tensor(y_train.values, dtype=torch.float)

y_test_tensor = torch.tensor(y_test.values, dtype=torch.float)

print(X_train_tensor)
print(y_train_tensor)

tensor([[ 0.6782,  0.2356, -0.0050,  ..., -0.2664, -0.6382, -0.9602],
        [ 0.3334, -0.1554, -0.3131,  ...,  0.1224,  1.0141,  0.6355],
        [-0.5069,  0.7033, -0.9548,  ...,  1.6573,  0.2100,  0.5119],
        ...,
        [-0.1759, -0.9300,  0.9123,  ...,  0.2520,  1.0285,  2.0638],
        [ 2.0570, -0.8258,  1.2274,  ..., -0.4608,  0.6011, -0.0216],
        [ 1.3634, -0.9986,  1.3306,  ..., -1.0553, -0.0493,  0.5494]])
tensor([5., 6., 7.,  ..., 8., 6., 8.])


In [234]:
X_train_tensor.dtype

torch.float32