# Source

[Wine quality prediction using PyTorch](https://medium.com/analytics-vidhya/wine-quality-prediction-using-pytorch-2a291670dd66#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjBlNzJkYTFkZjUwMWNhNmY3NTZiZjEwM2ZkN2M3MjAyOTQ3NzI1MDYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJhenAiOiIyMTYyOTYwMzU4MzQtazFrNnFlMDYwczJ0cDJhMmphbTRsamRjbXMwMHN0dGcuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJhdWQiOiIyMTYyOTYwMzU4MzQtazFrNnFlMDYwczJ0cDJhMmphbTRsamRjbXMwMHN0dGcuYXBwcy5nb29nbGV1c2VyY29udGVudC5jb20iLCJzdWIiOiIxMDkxMTc0MTkxNzMyOTg0OTU4MzciLCJoZCI6InByZWRkYXRhLmNvbSIsImVtYWlsIjoidmljdG9yLnBlY2luZUBwcmVkZGF0YS5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmJmIjoxNzAxMTY4MDYyLCJuYW1lIjoiVmljdG9yIFBlY2luZSB8IFByZWRkYXRhIFNvbHV0aW9ucyIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NMRzh2Zk5ZeWlmUVVZakNxMHBBdElsVWNDNi0zejAzYm5lRTg5clNqalY9czk2LWMiLCJnaXZlbl9uYW1lIjoiVmljdG9yIFBlY2luZSIsImZhbWlseV9uYW1lIjoifCBQcmVkZGF0YSBTb2x1dGlvbnMiLCJsb2NhbGUiOiJwdC1CUiIsImlhdCI6MTcwMTE2ODM2MiwiZXhwIjoxNzAxMTcxOTYyLCJqdGkiOiI2Mjk4NDM1MjYyNzY0ZTQxYWRjNjNkZGI4ZTIzMjg4ZDhjODU0NjQxIn0.X9PkBXf0xEbQGAlsMyiOeT5jQ2q7M-Q7QA8XAcC2y0oK6L1c_MYoKas62UQ6mhqab6ZGs8tUFDoFGV6oLrV8IEz9Nzx1-CEbezYfVjtK_delT3WpD33mtctmIyfsJi3wweldaTVtRh8_24YZSuYfiXUjPCJ9O3up4V4i1quFNg7SppfHnFXzA28VIIUVqkumFb0Leb8mk-fPdmBUQSNMZSe-2PzfYDw3RtcKuR32l_7VGhNsuqOh2TUhROfZ0w5cajcGOuM0iR-nZcQxfOpzxeeGpDnnH0rMgY1cZov5UWDHjPieC6JcL1AsX2PoG6ka-lqPuzwepgxURfMC3kjBMA)

# Steps

✔️ Data wrangling

✔️ Data visualization

✔️ Scaling data

✔️ Resampling data

➖ RNN

➖ Loss function

# Libraires

In [254]:
# !pip install plotly -U --quiet

In [255]:
import  torch
import  matplotlib.pyplot as plt
import  numpy as np
import  pandas as pd
import  plotly.express as px

from    google.colab import drive
from    sklearn.model_selection import train_test_split
from    sklearn.preprocessing import StandardScaler
from    imblearn.over_sampling import SMOTE
from    imblearn.combine import SMOTEENN
from    torch import nn

In [256]:
seed = np.random.seed(31)

In [257]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# Dataset

In [258]:
df_wine = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/winequality-red.csv',
                      sep=',',
                      encoding='utf-8')

df_wine

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [259]:
df_wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [260]:
df_wine.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [261]:
df_wine['quality'].unique()

array([5, 6, 7, 4, 8, 3])

In [262]:
df_wine['quality'].replace([3, 4, 5, 6, 7, 8], [0, 1, 2, 3, 4, 5],
                           inplace=True)

In [263]:
df_wine.head(10)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   
5            7.4              0.66         0.00             1.8      0.075   
6            7.9              0.60         0.06             1.6      0.069   
7            7.3              0.65         0.00             1.2      0.065   
8            7.8              0.58         0.02             2.0      0.073   
9            7.5              0.50         0.36             6.1      0.071   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   
5                 13.0                  40.0   0.9978  3.51       0.56   
6                 15.0                  59.0   0.9964  3.30       0.46   
7                 15.0                  21.0   0.9946  3.39       0.47   
8                  9.0                  18.0   0.9968  3.36       0.57   
9                 17.0                 102.0   0.9978  3.35       0.80   

   alcohol  quality  
0      9.4        2  
1      9.8        2  
2      9.8        2  
3      9.8        3  
4      9.4        2  
5      9.4        2  
6      9.4        2  
7     10.0        4  
8      9.5        4  
9     10.5        2

# Data visualization

In [264]:
fig = px.histogram(df_wine, x='quality')
fig.show()

It's a good practice over-sampling the data to have a equal balance

In [265]:
df_wine['quality'].value_counts()

2    681
3    638
4    199
1     53
5     18
0     10
Name: quality, dtype: int64

In [266]:
maior_quantidade_qualidade = df_wine['quality'].value_counts().max()

maior_quantidade_qualidade

681

# Resampling data

In [267]:
X = df_wine.drop(columns='quality')

y = df_wine['quality']

In [268]:
smoteenn = SMOTEENN()

X_smoteenn, y_smoteenn = smoteenn.fit_resample(X, y)

In [269]:
smote = SMOTE()

X_smote, y_smote = smote.fit_resample(X, y)

In [270]:
print('Shape of X_smoteenn: ', X_smoteenn.shape)
print('Shape of y_smoteenn: ', y_smoteenn.shape)

print('Shape of X_smote: ', X_smote.shape)
print('Shape of y_smote: ', y_smote.shape)

Shape of X_smoteenn:  (2402, 11)
Shape of y_smoteenn:  (2402,)
Shape of X_smote:  (4086, 11)
Shape of y_smote:  (4086,)


In [271]:
df_wine_smoteenn = pd.DataFrame(np.column_stack((X_smoteenn, y_smoteenn)))

df_wine_smoteenn.rename(columns={0:  df_wine.columns[0],
                                 1:  df_wine.columns[1],
                                 2:  df_wine.columns[2],
                                 3:  df_wine.columns[3],
                                 4:  df_wine.columns[4],
                                 5:  df_wine.columns[5],
                                 6:  df_wine.columns[6],
                                 7:  df_wine.columns[7],
                                 8:  df_wine.columns[8],
                                 9:  df_wine.columns[9],
                                 10: df_wine.columns[10],
                                 11: df_wine.columns[11]},
                        inplace=True)

df_wine_smoteenn.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0           11.6             0.580         0.66            2.20      0.074   
1           10.4             0.610         0.49            2.10      0.200   
2            7.4             1.185         0.00            4.25      0.097   
3           10.4             0.440         0.42            1.50      0.145   
4            8.3             1.020         0.02            3.40      0.084   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 10.0                  47.0  1.00080  3.25       0.57   
1                  5.0                  16.0  0.99940  3.16       0.63   
2                  5.0                  14.0  0.99660  3.63       0.54   
3                 34.0                  48.0  0.99832  3.38       0.86   
4                  6.0                  11.0  0.99892  3.48       0.49   

   alcohol  quality  
0      9.0      0.0  
1      8.4      0.0  
2     10.7      0.0  
3      9.9      0.0  
4     11.0      0.0

In [272]:
fig = px.histogram(df_wine_smoteenn, x='quality')

fig.show()

In [273]:
df_wine_smote = pd.DataFrame(np.column_stack((X_smote, y_smote)))

df_wine_smote.rename(columns={0: df_wine.columns[0],
                                   1: df_wine.columns[1],
                                   2: df_wine.columns[2],
                                   3: df_wine.columns[3],
                                   4: df_wine.columns[4],
                                   5: df_wine.columns[5],
                                   6: df_wine.columns[6],
                                   7: df_wine.columns[7],
                                   8: df_wine.columns[8],
                                   9: df_wine.columns[9],
                                   10: df_wine.columns[10],
                                   11: df_wine.columns[11]},
                          inplace=True)

df_wine_smote.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4      2.0  
1      9.8      2.0  
2      9.8      2.0  
3      9.8      3.0  
4      9.4      2.0

In [274]:
fig = px.histogram(df_wine_smote, x='quality')

fig.show()

# Scaling train test split

In [275]:
X_train, X_test, y_train, y_test = train_test_split(X_smote,
                                                    y_smote,
                                                    test_size=0.3,
                                                    random_state=seed)

print('Shape of X_train: ', X_train.shape)
print('Shape of X_test: ', X_test.shape)
print('Shape of y_train: ', y_train.shape)
print('Shape of y_test: ', y_test.shape)

Shape of X_train:  (2860, 11)
Shape of X_test:  (1226, 11)
Shape of y_train:  (2860,)
Shape of y_test:  (1226,)


In [276]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

Notice that we use .fit_transform() on X_train while we use .transform() on X_val and X_test.

We do this because we want to scale the validation and test set with the same parameters as that of the train set to avoid data leakage. fit_transform calculates scaling values and applies them while .transform only applies the calculated values.

Source: https://towardsdatascience.com/pytorch-tabular-multiclass-classification-9f8211a123ab

In [277]:
print('Shape of X_train_scaled: ', X_train_scaled.shape)
print('Shape of X_test_scaled: ', X_test_scaled.shape)

Shape of X_train_scaled:  (2860, 11)
Shape of X_test_scaled:  (1226, 11)


# Tensors

In [280]:
# Check available hardware
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')

print(device)

cuda


In [281]:
X_train_tensor = torch.tensor(X_train_scaled).float().to(device)

X_test_tensor = torch.tensor(X_test_scaled).float().to(device)

y_train_tensor = torch.LongTensor(y_train.values).to(device)

y_test_tensor = torch.LongTensor(y_test.values).to(device)

print(X_train_tensor)
print(y_train_tensor)

tensor([[ 0.6596, -0.0618, -0.0222,  ..., -0.3712, -0.7002, -1.1287],
        [ 0.3013, -0.3452, -0.3151,  ...,  0.0254,  1.0878,  0.3270],
        [-0.3038, -0.0448, -0.5142,  ...,  1.4059,  0.3252,  0.0220],
        ...,
        [ 0.1594, -0.9788,  1.1114,  ..., -0.3463,  1.2380,  1.3660],
        [ 2.0926, -0.8310,  1.1496,  ..., -0.5695,  0.6408, -0.2724],
        [-0.2828, -0.9563,  0.9095,  ...,  0.1324,  1.2642,  1.7738]],
       device='cuda:0')
tensor([2, 3, 4,  ..., 5, 3, 5], device='cuda:0')


# Multilayer perceptron

In [282]:
input_size = X.shape[1]

hidden_size = 32

output_size = len(y.unique())

In [283]:
args = {'batch_size': 5,
        'num_workers': 4,
        'num_classes': output_size,
        'lr': 0.0001,
        'weight_decay': 0.0005,
        'num_epochs': 30}

In [284]:
class WineClassifier(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(WineClassifier, self).__init__()

        # Neural Net architecture
        # Hidden layer
        self.hidden = nn.Linear(input_size, hidden_size)
        self.activation = nn.ReLU()

        # Output layer
        self.out = nn.Linear(hidden_size, output_size)
        self.softmax = nn.Softmax(dim=1)  # Probability distribution

    def forward(self, x):
        hidden = self.activation(self.hidden(x))
        output = self.softmax(self.out(hidden))

        return output

## Net

In [285]:
net = WineClassifier(input_size, hidden_size, output_size).to(device)

In [286]:
pred = net(X_train_tensor)

pred.shape

torch.Size([2860, 6])

In [287]:
pred

tensor([[0.1221, 0.1112, 0.1654, 0.2909, 0.2202, 0.0903],
        [0.1635, 0.1492, 0.1489, 0.1977, 0.1916, 0.1491],
        [0.1769, 0.1542, 0.1718, 0.2048, 0.1545, 0.1378],
        ...,
        [0.1661, 0.1636, 0.1510, 0.1729, 0.1970, 0.1496],
        [0.1732, 0.1676, 0.1307, 0.1703, 0.2305, 0.1277],
        [0.1691, 0.1571, 0.1706, 0.1743, 0.1864, 0.1425]], device='cuda:0',
       grad_fn=<SoftmaxBackward0>)

In [288]:
criterion = nn.CrossEntropyLoss().to(device)  # Loss

loss = criterion(pred, y_train_tensor)

loss

tensor(1.7879, device='cuda:0', grad_fn=<NllLossBackward0>)